# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 2.3.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /home/ruoyi/uploadPath
  #  profile: C:\lmc\project\render-java
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 3003
# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.6.0.66:5432/farmdb?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: farmman
    password: farm123@
